#!/bin/tcsh
#SBATCH --qos=interactive       # standard, interactive or standby
#SBATCH --time=4:00:00
#SBATCH --nodes=32
#SBATCH --ntasks-per-node=16
#SBATCH --output slurm%j.out
#SBATCH --error slurm%j.err
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --mail-user=guofan@lanl.gov
##SBATCH -A account_name     # slurm account 

# Shell commands
date
echo '*** Staring Parallel Job ***'
module load gcc openmpi

# srun ./test
srun -n 512 ./turbulence-sheet-tracer2spec.cxx.op

date
echo '*** All Done ***'
# 

