# Define shell
SHELL = csh

all:

#	$(HOME)/vpic-407-mustang/build-h5s.op turbulence-sheet-tracer.cxx
	/users/guofan/vpic-407-trinitite/build.op turbulence-sheet-tracer.cxx


cleanall: 	
#	cd translate; make clean 
	-rm data/*
	-rm -rf hydro
	-rm -rf particle
	-rm -rf restart*
	-rm -rf rundata
	-rm -rf fields
#	-rm translate
	-rm *.op
	-rm *.ppu
	-rm *.vpc
	-rm outfile
	-rm info
	-rm *.eps
	-rm *.mpg
	-rm core.*
	-rm *~









