#!/bin/tcsh
#MSUB -l walltime=2:00:00
#MSUB -l nodes=16:ppn=16
#MSUB -N Rogers
#MSUB -j oe
#MSUB -o outfile2
#MSUB -m abe


# Now run the script as this group - so all data files will belong

#  Shell commands
date
echo '*** Staring Parallel Job ***'
module load intel
module load openmpi/1.4.5
#mpirun -np 2048 --mca mpi_paffinity_alone 0 ./sforce_free_mpert.cxx.op -tpp=2 restart restart1/restart >& outfile2
#mpirun -np 2048 --mca mpi_paffinity_alone 0 ./sigma.cxx.op -tpp=2
mpirun -np 256 ./translate
#mpirun -np 512 ./sigma.cxx.op restart restart0/restart

# restart restart0/restart
date
echo '*** All Done ***'

# 
